### ISSUE TITLE
Runtime Error ReferenceError: AbortSignal is not defined

### ISSUE THREAD

**Issue by ByeongsuPark** [julyydev/auto-judge#3]
# Issue
When running auto-judge, I got runtime error with the following error message.
```
ReferenceError: AbortSignal is not defined
```

# Screenshot

![image](https://github.com/julyydev/auto-judge/assets/39683194/bb53f0df-94c4-4764-a1e8-ff347b154ae9)

**Comment by zudydy** [comment]
Check your node version.

A timeout is output after 2 seconds for each test case, which uses `AbortSignal` to cancel asynchronous operations.
This `AbortSignal` is available from version v16.5.0 of node.

Therefore, I suspect a problem with the node version.
If you are using a lower version, please upload the version and try again. :)

**Comment by ByeongsuPark** [comment]
Thank you for reviewing this issue. The error mentioned above is resolved after the node version update
If the requirement of node version mentioned in README, it would be great!
Thanks.
